const MerchantApplyData = {
  timestamp: '',
  method: '',
  partner_id: '',
  sign_type: '',
  hash_type: '',
  version: '',
  biz_content: {
    merchant_name: '',
    fax: "",
    agent_id: '',
    contact_name: '',
    mobile: '',
    email: '',
    category_id: '',
    storeshortname: '',
    property: '',
    mchdealtype: '',
    mcc: '',
    province_code: '',
    city_code: '',
    district_code: '',
    address: '',
    business_time: '',
    contact_type: '',
    contact_number: '',
    contact_province: '',
    contact_city: '',
    contact_area: '',
    contact_address: '',
    main_image: '',
    shop_place_image: '',
    shop_product_image: '',
    shop_cashier_image: '',
    shop_cas: '',
    // hier_image: '',
    enterprise_type: '',
    org_code: '',
    licence_name: '',
    busi_address: '',
    busi_legal_name: '',
    reg_capital: '',
    busi_province: '',
    busi_city: '',
    busi_area: '',
    busi_start: '',
    busi_end: '',
    busi_license_image: '',
    legal_id_type: '',
    legal_id_image1: '',
    legal_id_image2: '',
    legal_id_image3:'',
    legal_id_image4:'',
    legal_id_image5: '',
    bankcard_image1:'',
    bankcard_image2:'',
    legal_id_start: '',
    legal_id_end: '',
    legal_name: '',
    legal_id_no: '',
    accounttype: '',
    accountname: '',
    account_code: '',
    bankname: '',
    sub_bank_name: '',
    open_bank_pro: '',
    open_bank_city: '',
    tel: ''
  }
}
export default MerchantApplyData